#!/bin/zsh

# directories
maildir="/Users/sulrich/mail"
archdir=".archives"

# mbox lists
csco_mboxlist=/Users/sulrich/bin/data/cisco-mboxlist
   q_mboxlist=/Users/sulrich/bin/data/qwest-mboxlist
list_mboxlist=/Users/sulrich/bin/data/list-mboxlist

# get last month - current_date (in seconds) - 1_week (in seconds),
cur_month=`date +%s`
last_yr=`date -r $(( $cur_month - 604800 )) +%Y`
last_mo=`date -r $(( $cur_month - 604800 )) +%m`
echo ${last_yr}-${last_mo}

# stop fetchmail for this process
/usr/bin/fetchmail -q

#---------------------------------------------------------------------
# big mail directories
#

# cisco archives
# foreach i (`cat ${csco_mboxlist}`) 
#   mv ${maildir}/cisco/$i \
#      ${maildir}/cisco/${archdir}/${last_yr}/$i-${last_yr}-${last_mo}
# 
#   gzip -9 ${maildir}/cisco/${archdir}/${last_yr}/$i-${last_yr}-${last_mo}
#   touch ${maildir}/cisco/$i ; chmod 0700 ${maildir}/cisco/$i
# end

# qwest archives
foreach i (`cat ${q_mboxlist}`) 
  mv ${maildir}/qwest/$i \
     ${maildir}/qwest/${archdir}/${last_yr}/$i-${last_yr}-${last_mo}

  gzip -9 ${maildir}/qwest/${archdir}/${last_yr}/$i-${last_yr}-${last_mo}
  touch ${maildir}/qwest/$i ; chmod 0700 ${maildir}/qwest/$i
end

# misc. mailing lists
foreach i (`cat ${list_mboxlist}`) 
  mv ${maildir}/lists/$i \
     ${maildir}/lists/${archdir}/${last_yr}/$i-${last_yr}-${last_mo}

  gzip -9 ${maildir}/lists/${archdir}/${last_yr}/$i-${last_yr}-${last_mo}
  touch ${maildir}/lists/$i ; chmod 0700 ${maildir}/lists/$i
end

#---------------------------------------------------------------------
# misc cleanup

# read mail
mv ${maildir}/read_mail \
   ${maildir}/read_mail_archives/${last_yr}/${last_yr}-${last_mo}

gzip -9 ${maildir}/read_mail_archives/${last_yr}/${last_yr}-${last_mo}
touch ${maildir}/read_mail ; chmod 0700 ${maildir}/read_mail 

# sent mail
mv ${maildir}/outbox \
   ${maildir}/sent_mail_archives/${last_yr}/${last_yr}-${last_mo}

gzip -9 ${maildir}/sent_mail_archives/${last_yr}/${last_yr}-${last_mo}
touch ${maildir}/outbox ; chmod 0700 ${maildir}/outbox

# handle the logs
cp /dev/null ${maildir}/logs/fetchmail
cp /dev/null ${maildir}/logs/procmail

# start fetchmail back up
# /usr/bin/fetchmail -d120
