#!/bin/bash

MAILDIR=${HOME}/mail

# create the appropriate directories
mkdir ${MAILDIR}/$1
mkdir ${MAILDIR}/$1/{tmp,cur,new}

# set the appropriate permissions
chown -R sulrich:"JNPR\others" ${MAILDIR}/$1
chmod -R 0700            ${MAILDIR}/$1
